# Generated by Django 4.2.6 on 2023-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_comment_parent_remove_comment_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
