# Generated by Django 4.2.6 on 2023-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_videolikes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('MUSIC', 'music'), ('SERMON', 'sermon'), ('PREACHING', 'preaching'), ('BIBLE_STUDY', 'bible_study'), ('PRAISE_AND_WORSHIP', 'praise_and_worship'), ('ALL_TESTIMONIES', 'all_testimonies'), ('BIBLE_DISCUSSIONS', 'bible_discussions'), ('EVANGELISM', 'evangelism'), ('STREET_PRAISE_AND_WORSHIP_MUSIC_AND_PREACHING', 'street_worship_music'), ('GOSPEL_MADE_FOR_KIDS', 'gospel_made_for_kids')], default='MUSIC', max_length=50),
        ),
    ]
