# Generated by Django 4.2.6 on 2023-11-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='video',
        ),
    ]
