# Generated by Django 4.2.6 on 2023-11-14 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_notifications_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, unique=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('subd', models.ManyToManyField(related_name='subd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
