# Generated by Django 4.2.6 on 2023-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_category'),
        ('users', '0013_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_videos',
            field=models.ManyToManyField(to='videos.video'),
        ),
    ]
